routes/authentication.py
# Creating all necessary imports  creaating a blueprint and then creating four routes that
# handle registration, profile, login and logout.
# In registration route im crating function that recives data from registration form then checks if
# username is available if not redirects back to register page if available generates hashed password 
# and then saves users data to database and redirects to home page.
# In profile route just setting up login required decorator to acces the page only if logged in
# and function profile that gets all currently logged in users reviews and returns profile page.
# Login route here we have login functionn that requests username and password  and if they match
# user gets logged in and redirected to home page. 
# Just like profile page only can be accesed if user is logged in and the rout just redirects to login page
# after logout is comfirmed. 

from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from models import User, Review, db
from datetime import datetime

authentication = Blueprint('authentication', __name__)

@authentication.route('/register', methods=["POST", "GET"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        email = request.form["email"]
        date = request.form["date"]
        join_date = datetime.strptime(date, "%Y-%m-%d").date()

        if User.query.filter_by(username=username).first():
            return redirect(url_for("authentication.register"))

        hashed_password = generate_password_hash(password)
        user = User(username=username, password=hashed_password, email=email, join_date=join_date)

        db.session.add(user)
        db.session.commit()

        login_user(user)
        return redirect(url_for('pages.home'))
    
    return render_template('register.html')


@authentication.route('/profile', methods=['GET','POST'])
@login_required
def profile(): 
    user_reviews = Review.query.filter_by(user_id=current_user.user_id).all()

    return render_template('profile.html', user=current_user, reviews=user_reviews)


@authentication.route('/login', methods=["POST", "GET"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('pages.home'))
        else:
            return redirect(url_for('authentication.login'))

    return render_template('login.html')


@authentication.route('/logout', methods=['GET','POST'])
@login_required
def logout():
    if request.method == 'POST':
        logout_user()
        return redirect(url_for('authentication.login'))
    return render_template('logout.html')

routes/pages.py
# Creating all necessary imports creating a blueprint and then creating a function that quaries
# database and fetches data from tours and reviews of associated city.
# Each city route renders tamplate for the city and displayes the data for city tours and reviews.
# Home route just renders index.html (home page).

from flask import Blueprint, render_template
from flask_login import login_required, current_user
from models import User, Tour, Review, db

pages = Blueprint('pages', __name__)

def fetch_city_data(city_name):
    tours = Tour.query.filter_by(city=city_name).all()
    reviews = (
        Review.query
        .join(Tour, Review.tour_id == Tour.tour_id)
        .join(User, Review.user_id == User.user_id)
        .filter(Tour.city == city_name)
        .all()
    )
    return tours, reviews


@pages.route('/')
def home():
    return render_template('index.html')

@pages.route('/london')
def london():
    tours, reviews = fetch_city_data("London")
    return render_template('london.html', tours=tours, reviews=reviews)

@pages.route('/glasgow')
def glasgow():
    tours, reviews = fetch_city_data("Glasgow")
    return render_template('glasgow.html', tours=tours, reviews=reviews)

@pages.route('/dublin')
def dublin():
    tours, reviews = fetch_city_data("Dublin")
    return render_template('dublin.html', tours=tours, reviews=reviews)

@pages.route('/cardiff')
def cardiff():
    tours, reviews = fetch_city_data("Cardiff")
    return render_template('cardiff.html', tours=tours, reviews=reviews)

routes/reviews.py
# Creating all necessary imports, creating a blueprint and three routes that  handle submitting review,
# editing review and deleting review. 
# All three routes require user to be authenticated in first route we have a function that gets tour id and review content
# from the form and then saves it with users id and redirects to city page. 
# In second route we have function that gets review id checks that the current user is owner of the review if edited commits new
# content to database and returns to next page (profile or city page). 
# And third route function just gets the review id makes sure current user owns the review and deletes the review
# commits change and redirect just like in previous route.

from flask import Blueprint, request, redirect, url_for ,render_template
from flask_login import current_user, login_required
from models import Review, db

reviews = Blueprint('reviews', __name__)

@reviews.route('/submit_review/<string:city>', methods=['POST'])
@login_required
def submit_review(city):
    tour_id = request.form.get("tour_id")
    review_content = request.form.get("review_content")

    if not tour_id or not review_content:
        return redirect(url_for(f'pages.{city}'))

    review = Review(
        user_id=current_user.user_id,
        tour_id=tour_id,
        review_content=review_content
    )
    db.session.add(review)
    db.session.commit()

    return redirect(url_for(f'pages.{city}'))

@reviews.route('/edit/<int:review_id>', methods=['GET', 'POST'])
@login_required
def edit_review(review_id):
    review = Review.query.get_or_404(review_id)

    if review.user_id != current_user.user_id:
        return "Unauthorized", 403

    next_page = request.args.get('next') or url_for(f'pages.{review.tour.city.lower()}')

    if request.method == 'POST':
        new_content = request.form.get('review_content')
        if new_content:
            review.review_content = new_content
            db.session.commit()
            return redirect(next_page)

    return render_template('edit_review.html', review=review, next_page=next_page)

@reviews.route('/delete/<int:review_id>', methods=['POST'])
@login_required
def delete_review(review_id):
    review = Review.query.get_or_404(review_id)

    if review.user_id != current_user.user_id:
        return "Unauthorized", 403

    next_page = request.form.get('next') or url_for(f'pages.{review.tour.city.lower()}')

    db.session.delete(review)
    db.session.commit()
    return redirect(next_page)

templates/base.html
<!-- 
    In base tamplate we have links for css and font, navigation that contains dynamic links that change depending on users authentication status
    and other links to navigate trough website.
    Footer with link to home page and contact, and after that tag for javascript.
-->

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Big City Tour</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@300..800&family=Lora:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
    </head>
    <body class="wrapper">
        <header>
            <ul class="nav">
                <li class="logo"><h1>Big City Tour</h1></li>
                <li><a href="{{ url_for('pages.home') }}">Home</a></li>
                <li class="dropdown">
                    <a>Cities</a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('pages.london') }}">London</a></li>
                        <li><a href="{{ url_for('pages.glasgow') }}">Glasgow</a></li>
                        <li><a href="{{ url_for('pages.dublin') }}">Dublin</a></li>
                        <li><a href="{{ url_for('pages.cardiff') }}">Cardiff</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a>User</a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('authentication.profile') }}">Profile</a></li>
                        <li><a href="{{ url_for('authentication.logout') }}">Log Out</a></li>
                        {% else %}
                        <li><a href="{{ url_for('authentication.register') }}">Register</a></li>
                        <li><a href="{{ url_for('authentication.login') }}">Log In</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <ul class="nav">
                <li><a href="{{ url_for('pages.home') }}">Home</a></li>
                <li><a href="mailto:ledenko96@gmail.com">Contact</a></li>
            </ul>
            <p>&copy; 2024 Big City Tours. All rights reserved.</p>
        </footer>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </body>
</html>

templates/cardiff.html
<!-- 
    All city page have same code structure tours are displayed with jinja for loop that displays tour name and content. 
    Similar to tours reviews are displayed the same way just with the form only visable to authenticated user for editing or deleting their reviews.
    And leave a review form contains textare for contnet input a dropdown select that provides option to select tour for which user is making a review by gettinng tours id 
    and a submit button to post review.
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Cardiff Tour</h1>
<div class="tours">
    {% for tour in tours %}
    <div>
        <h2 class="h1c">{{ tour.tour_name }}</h2>
        <p class="p1">{{ tour.tour_content }}</p>
    </div>
    {% endfor %}
</div>
<div class="imgdiv">
    <img src="{{ url_for('static', filename='images/cardiff-castle.png') }}" alt="cardiff castle">
    <img src="{{ url_for('static', filename='images/st-fagans.png') }}" alt="st fagans museum">
    <img src="{{ url_for('static', filename='images/cardiff-bay.png') }}" alt="cardiff bay">
    <img src="{{ url_for('static', filename='images/principality-stadium.png') }}" alt="principality stadium">
</div>
<h2 class="h1c">Reviews</h2>
    <div class="review">
        {% for review in reviews %}
        <div class="review1">
            <p class="p1">{{ review.review_content }}</p>
            <p class="p1">By {{ review.created_by.username }}</p>
            <p class="p1">Tour: {{ review.tour.tour_name }}</p>
            {% if current_user.username == review.created_by.username %}
            <form method="POST" action="{{ url_for('reviews.delete_review', review_id=review.review_id) }}" style="display:inline;">
                <input type="hidden" name="next" value="{{ url_for('pages.cardiff') }}">
                <button class="button" type="submit" onclick="return confirm('Are you sure you want to delete this review?')">Delete</button>
                <a class="button" href="{{ url_for('reviews.edit_review', review_id=review.review_id, next=url_for('pages.cardiff')) }}">Edit</a>
            </form>
            {% endif %}
        </div>
    {% endfor %}
    </div>
<h2 class="h1c">Leave a Review</h2>
<form class="form" method="POST" action="{{ url_for('reviews.submit_review', city='cardiff') }}">
    <label for="review_content">Your Review:</label>
    <textarea name="review_content" id="review_content" rows="5" required></textarea>
    <label for="tour_id">Select a Tour:</label>
    <select name="tour_id" id="tour_id" required>
        {% for tour in tours %}
        <option value="{{ tour.tour_id }}">{{ tour.tour_name }}</option>
        {% endfor %}
    </select>
    <button class="button" type="submit">Submit Review</button>
</form>
{% endblock %}

templates/dublin.html
<!-- 
    All city page have same code structure tours are displayed with jinja for loop that displays tour name and content. 
    Similar to tours reviews are displayed the same way just with the form only visable to authenticated user for editing or deleting their reviews.
    And leave a review form contains textare for contnet input a dropdown select that provides option to select tour for which user is making a review by gettinng tours id 
    and a submit button to post review.
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Dublin Tour</h1>
<div class="tours">
    {% for tour in tours %}
    <div>
        <h2 class="h1c">{{ tour.tour_name }}</h2>
        <p class="p1">{{ tour.tour_content }}</p>
    </div>
    {% endfor %}
</div>
<div class="imgdiv">
    <img src="{{ url_for('static', filename='images/guinness-storehouse.png') }}" alt="guinness storehouse">
    <img src="{{ url_for('static', filename='images/trinity-college.png') }}" alt="trinity college">
    <img src="{{ url_for('static', filename='images/dublin-castle.png') }}" alt="dublin castle">
    <img src="{{ url_for('static', filename='images/phoenix-park.png') }}" alt="phoenix park">
</div>
<h2 class="h1c">Reviews</h2>
    <div class="review">
        {% for review in reviews %}
        <div class="review1">
            <p class="p1">{{ review.review_content }}</p>
            <p class="p1">By {{ review.created_by.username }}</p>
            <p class="p1">Tour: {{ review.tour.tour_name }}</p>
            {% if current_user.username == review.created_by.username %}
            <form method="POST" action="{{ url_for('reviews.delete_review', review_id=review.review_id) }}" style="display:inline;">
                <input type="hidden" name="next" value="{{ url_for('pages.dublin') }}">
                <button class="button" type="submit" onclick="return confirm('Are you sure you want to delete this review?')">Delete</button>
                <a class="button" href="{{ url_for('reviews.edit_review', review_id=review.review_id, next=url_for('pages.dublin')) }}">Edit</a>
            </form>
            {% endif %}
        </div>
    {% endfor %}
    </div>
<h2 class="h1c">Leave a Review</h2>
<form class="form" method="POST" action="{{ url_for('reviews.submit_review', city='dublin') }}">
    <label for="review_content">Your Review:</label>
    <textarea name="review_content" id="review_content" rows="5" required></textarea>
    <label for="tour_id">Select a Tour:</label>
    <select name="tour_id" id="tour_id" required>
        {% for tour in tours %}
        <option value="{{ tour.tour_id }}">{{ tour.tour_name }}</option>
        {% endfor %}
    </select>
    <button class="button" type="submit">Submit Review</button>
</form>
{% endblock %}

templates/edit_review.html
<!--
    This form allows user to edit data textarea already contains review content that can be changed 
    with editing and clicing on save changes button. Cancel button (link) just redirects to last page.
    By clicking on save changes were sending data to edit review route.
-->

{% extends 'base.html' %}
{% block content %}
<h1>Edit Your Review</h1>
<form class="form" action="{{ url_for('reviews.edit_review', review_id=review.review_id,
next=request.args.get('next', url_for('pages.' + review.tour.city.lower()))) }}" method="POST">
    <label for="review_content">Review:</label>
    <textarea name="review_content" id="review_content" rows="5" cols="50">{{ review.review_content }}</textarea>
    <button class="button" type="submit">Save Changes</button>
    <a class="button" href="{{ request.args.get('next', url_for('pages.' + review.tour.city.lower())) }}">Cancel</a>
</form>
{% endblock %}

templates/glasgow.html
<!-- 
    All city page have same code structure tours are displayed with jinja for loop that displays tour name and content. 
    Similar to tours reviews are displayed the same way just with the form only visable to authenticated user for editing or deleting their reviews.
    And leave a review form contains textare for contnet input a dropdown select that provides option to select tour for which user is making a review by gettinng tours id 
    and a submit button to post review.
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Glasgow Tour</h1>
<div class="tours">
    {% for tour in tours %}
    <div>
        <h2 class="h1c">{{ tour.tour_name }}</h2>
        <p class="p1">{{ tour.tour_content }}</p>
    </div>
    {% endfor %}
</div>
<div class="imgdiv">
    <img src="{{ url_for('static', filename='images/kelvingrove.png') }}" alt="kelvingrove museum">
    <img src="{{ url_for('static', filename='images/glasgow-cathedral.png') }}" alt="glasgow cathedral">
    <img src="{{ url_for('static', filename='images/riverside-museum.png') }}" alt="riverside museum">
    <img src="{{ url_for('static', filename='images/glasgow-necropolis.png') }}" alt="glasgow necropolis">
</div>
<h2 class="h1c">Reviews</h2>
    <div class="review">
        {% for review in reviews %}
        <div class="review1">
            <p class="p1">{{ review.review_content }}</p>
            <p class="p1">By {{ review.created_by.username }}</p>
            <p class="p1">Tour: {{ review.tour.tour_name }}</p>
            {% if current_user.username == review.created_by.username %}
            <form method="POST" action="{{ url_for('reviews.delete_review', review_id=review.review_id) }}" style="display:inline;">
                <input type="hidden" name="next" value="{{ url_for('pages.glasgow') }}">
                <button class="button" type="submit" onclick="return confirm('Are you sure you want to delete this review?')">Delete</button>
                <a class="button" href="{{ url_for('reviews.edit_review', review_id=review.review_id, next=url_for('pages.glasgow')) }}">Edit</a>
            </form>
            {% endif %}
        </div>
    {% endfor %}
    </div>
<h2 class="h1c">Leave a Review</h2>
<form class="form" method="POST" action="{{ url_for('reviews.submit_review', city='glasgow') }}">
    <label for="review_content">Your Review:</label>
    <textarea name="review_content" id="review_content" rows="5" required></textarea>
    <label for="tour_id">Select a Tour:</label>
    <select name="tour_id" id="tour_id" required>
        {% for tour in tours %}
        <option value="{{ tour.tour_id }}">{{ tour.tour_name }}</option>
        {% endfor %}
    </select>
    <button class="button" type="submit">Submit Review</button>
</form>

{% endblock %}

templates/index.html
<!-- 
    On index page we just have some simple html with four image sliders. 
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Welcome</h1>
<p class="p2">
    Welcome to Big City Tours, where we take you through the biggest cities of England, Scotland, Ireland, and Wales.
    From the iconic landmarks of London to the cultural gems of Dublin, Glasgow, and Cardiff, our tours are designed to
    showcase the best these cities have to offer. Start your journey with us and explore the heart of the UK and Ireland!
</p>
<div class="tours">
    <div id="london-slider" class="slider">
        <img src="{{ url_for('static', filename='images/london1.png') }}" alt="london">
    </div>
    <div>
        <p class="p1">
            London is the largest city in England and the UK, as well as its capital. It’s a global hub of history, culture,
            and modern attractions. From the Tower of London to the bustling streets of Covent Garden, London offers a mix of historic
            landmarks and vibrant city life that’s unmatched anywhere in the world.
        </p>
    </div>
    <div>
        <p class="p1">
            Glasgow is Scotland’s largest city, famous for its art, music, and industrial heritage.
            It’s a city full of character, offering attractions like Kelvingrove Museum, Glasgow Cathedral,
            and the lively West End. Glasgow is a must-visit for anyone exploring Scotland.
        </p>
    </div>
    <div id="glasgow-slider" class="slider">
        <img src="{{ url_for('static', filename='images/glasgow1.png') }}" alt="glasgow">
    </div>
    <div id="dublin-slider" class="slider">
        <img src="{{ url_for('static', filename='images/dublin1.png') }}" alt="dublin">
    </div>
    <div>
        <p class="p1">
            Dublin is the capital and largest city of Ireland, known for its friendly locals and lively atmosphere.
            It’s a city where history and culture meet, with highlights like Trinity College, the Guinness Storehouse,
            and the beautiful Phoenix Park. Dublin is the perfect place to experience Irish charm.
        </p>
    </div>
    <div>
        <p class="p1">
            Cardiff is the capital and largest city of Wales, blending a rich history with a modern twist.
            Known for Cardiff Castle, the vibrant Cardiff Bay, and the Principality Stadium, this city is a true gem
            that showcases Welsh culture and hospitality.
        </p>
    </div>
    <div id="cardiff-slider" class="slider">
        <img src="{{ url_for('static', filename='images/cardiff1.png') }}" alt="cardiff">
    </div>
</div>
{% endblock %}

templates/login.html
<!--
    In this form user can authenticate by providing username and password by subiting data 
    with login button were sending data to login route.
-->

{% extends 'base.html' %}
{% block content %}
<h1>Log In</h1>
<form class="login" action="{{ url_for('authentication.login') }}" method="POST">
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    <button class="button" type="submit">Login</button>
</form>
{% endblock %}

templates/logout.html
<!--
    This page provides comfirmation form with a logout button that redirects to login page
    and a cancel button (link) that redirects to home page. 
-->
{% extends 'base.html' %}
{% block content %}
<form class="logout" action="{{ url_for('authentication.logout') }}" method="POST">
    <label>Are you sure you want to log out?</label>
    <button class="button" type="submit">Logout</button>
    <a class="button" href="{{ url_for('pages.home') }}">Cancel</a>
</form>
{% endblock %}

templates/london.html
<!-- 
    All city page have same code structure tours are displayed with jinja for loop that displays tour name and content. 
    Similar to tours reviews are displayed the same way just with the form only visable to authenticated user for editing or deleting their reviews.
    And leave a review form contains textare for contnet input a dropdown select that provides option to select tour for which user is making a review by gettinng tours id 
    and a submit button to post review.
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">London Tour</h1>
<div class="tours">
    {% for tour in tours %}
    <div>
        <h2 class="h1c">{{ tour.tour_name }}</h2>
        <p class="p1">{{ tour.tour_content }}</p>
    </div>
    {% endfor %}
</div>
<div class="imgdiv">
    <img src="{{ url_for('static', filename='images/british-museum.png') }}" alt="british museum">
    <img src="{{ url_for('static', filename='images/tower-of-london.png') }}" alt="tower of london">
    <img src="{{ url_for('static', filename='images/london-eye.png') }}" alt="london eye">
    <img src="{{ url_for('static', filename='images/hyde-park.png') }}" alt="hyde park">
</div>
<h2 class="h1c">Reviews</h2>
    <div class="review">
        {% for review in reviews %}
        <div class="review1">
            <p class="p1">{{ review.review_content }}</p>
            <p class="p1">By {{ review.created_by.username }}</p>
            <p class="p1">Tour: {{ review.tour.tour_name }}</p>
            {% if current_user.username == review.created_by.username %}
            <form method="POST" action="{{ url_for('reviews.delete_review', review_id=review.review_id) }}" style="display:inline;">
                <input type="hidden" name="next" value="{{ url_for('pages.london') }}">
                <button class="button" type="submit" onclick="return confirm('Are you sure you want to delete this review?')">Delete</button>
                <a class="button" href="{{ url_for('reviews.edit_review', review_id=review.review_id, next=url_for('pages.london')) }}">Edit</a>
            </form>
            {% endif %}
        </div>
     {% endfor %}
    </div>
<h2 class="h1c">Leave a Review</h2>
<form class="form" method="POST" action="{{ url_for('reviews.submit_review', city='london') }}">
    <label for="review_content">Your Review:</label>
    <textarea name="review_content" id="review_content" rows="5" required></textarea>
    <label for="tour_id">Select a Tour:</label>
    <select name="tour_id" id="tour_id" required>
        {% for tour in tours %}
        <option value="{{ tour.tour_id }}">{{ tour.tour_name }}</option>
        {% endfor %}
    </select>
    <button class="button" type="submit">Submit Review</button>
</form>
{% endblock %}

templates/profile.html
<!-- 
    Profile page displays logged in users username and all reviews written by user.
    Each review has a form with a delete button that on click triggers js confirm function and edit button (link) 
    that redirects user to edit review page.
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Welcome, {{ user.username }}</h1>

<h2 class="h1c">Your Reviews</h2>
{% if reviews %}
    {% for review in reviews %}
    <div class="review1">
        <p class="p1">{{ review.tour.city }}</p>
        <p class="p1">{{ review.tour.tour_name }}</p>
        <p class="p1">{{ review.review_content }}</p>
        <form method="POST" action="{{ url_for('reviews.delete_review', review_id=review.review_id) }}" style="display:inline;">
            <input type="hidden" name="next" value="{{ url_for('authentication.profile') }}">
            <button class="button" type="submit" onclick="return confirm('Are you sure you want to delete this review?')">Delete</button>
            <a class="button" href="{{ url_for('reviews.edit_review', review_id=review.review_id, next=url_for('authentication.profile')) }}">Edit</a>
        </form>
    </div>
    {% endfor %}
{% else %}
    <p>You haven't posted any comments yet.</p>
{% endif %}
{% endblock %}

templates/register.html
<!-- 
    Here we have just registration form with four inputs username, password, date and email 
    and a submit button. With submiting this form were sending data to register route. 
-->

{% extends 'base.html' %}
{% block content %}
<h1 class="h1c">Register</h1>
<form class="register" action="{{ url_for('authentication.register') }}" method="POST">
    <input type="text" name="username" placeholder="Username" required>
    <input type="text" name="password" placeholder="Password" required>
    <input type="date" name="date">
    <input type="text" name="email" placeholder="Email">
    <button class="button" type="submit">Submit</button>
</form>
{% endblock %}